### ISSUE TITLE
curl command example

### ISSUE THREAD

**Issue by the-jojo-jj** [open-wa/wa-automate-docker#13]
Hi, can somebody help with curl command example to send message?
thanks in advance.

**Comment by smashah** [comment]
@the-jojo-jj if you open the `/api-docs/` endpoint in a browser,

![image](https://user-images.githubusercontent.com/5903821/111773616-4e079300-88a6-11eb-883e-ee6b2d65bb21.png)

You can explore all the functions

![image](https://user-images.githubusercontent.com/5903821/111773828-94f58880-88a6-11eb-99a7-93e7134dff29.png)

and try them out


![image](https://user-images.githubusercontent.com/5903821/111773863-a0e14a80-88a6-11eb-829d-ea9cf88a3fa0.png)

edit the args, then hit execute

![image](https://user-images.githubusercontent.com/5903821/111774032-d0905280-88a6-11eb-8689-11d8d282ae99.png)

It will then show you the curl command used to make the request

![image](https://user-images.githubusercontent.com/5903821/111774136-f74e8900-88a6-11eb-9749-9c196fddce94.png)

**Comment by the-jojo-jj** [comment]
Thanks @smashah for your reply. 

this is my curl:

wget --no-check-certificate --quiet \
  --method POST \
  --timeout=0 \
  --header 'api_key: 4638ae9e1axxxxxxxxxx' \
   'https://api.xxxxx.xx/xx/xx/xxxxxx/sendText?to=4474472xxxxx@c.us'

and got: 

{
    "success": true,
    "response": "Message missing"
}


please help. thanks.

**Comment by the-jojo-jj** [comment]
I'm sorry. I was wrong.
