### ISSUE TITLE
ACCES: permission denied, mkdir 

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-docker#15]
After using new Docker file, I am getting following error

`EACCES: permission denied, mkdir '.node-persist' [Error: EACCES: permission denied, mkdir '.node-persist']`

@smashah  Can you please help me?

**Comment by smashah** [comment]
@manojsitapara I've pushed a fix for this. Please wait for the build + new image and try again:

https://github.com/open-wa/wa-automate-docker/runs/2581440687

**Comment by manojsitapara** [comment]
@smashah Thank you, will update issue after testing.

**Comment by manojsitapara** [comment]
It's working now. Thank you @smashah for your quick support and fix.
