### ISSUE TITLE
TypeError: Cannot read property 'camelCase' of undefined

### ISSUE THREAD

**Issue by malakaisbest** [open-wa/wa-automate-docker#16]
when i run `docker-compose up --build` it gives this issue

![openWA-docker](https://user-images.githubusercontent.com/12796396/120106736-e01bf980-c17b-11eb-945d-96236c7005b3.PNG)

**Comment by orlandobcr** [comment]
same here

**Comment by smashah** [comment]
fixed in latest image.

Please run 

```bash
> docker pull openwa/wa-automate:latest
```

and try again.

thanks
