### ISSUE TITLE
Deattaching from docker container console not possible?

### ISSUE THREAD

**Issue by CreativeWarlock** [open-wa/wa-automate-docker#18]
Hi,

I've been amazed by your great work! 

I've got a question. Please forgive me when my question is that of a beginner (since I am pretty new to Docker):

After running 
`docker run -e PORT=9090 -p 9090:9090 openwa/wa-automate:latest`

the terminal presents the QR code and then displays all the logged messages when I trigger various API calls shown on http://localhost:9090/api-docs/

But how can I de-attach from that console? Usually Ctrl+P and then Ctrl+Q allow us to detach from attached docker consoles.
Also closing through Ctrl-C or any interruption does not work.

What am I doing wrong or is this a missing feature? :)

Best regards
Marcel

**Comment by smashah** [comment]
@CreativeWarlock thanks for your patience

```bash
>  docker run -d openwa/wa-automate
```

should now work along with using ctrl+c to kill the process
