### ISSUE TITLE
Add --popup in docker file

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-docker#19]
To display QR code on browser, it required to run following docker command

docker run -e PORT=8080 -p 8080:8080 openwa/wa-automate:latest --popup

it is better we can specify --popup in the docker file, so user need not to specify it explicitly

Reference issue: https://github.com/open-wa/wa-automate-nodejs/issues/1866

**Comment by smashah** [comment]
crazy that this doesn't automatically turn it on:

https://github.com/open-wa/wa-automate-docker/blob/6f60566889ec0d8ada2b740fa31d71ba56a76488/Dockerfile#L39

anyways, I'll add this now before I head off to bed

**Comment by smashah** [comment]
Build:

https://github.com/open-wa/wa-automate-docker/runs/3038528496

If there are further issues let me know here and I will deal with them later.

thanks @manojsitapara
