### ISSUE TITLE
No Access on API Explorer

### ISSUE THREAD

**Issue by henning-kln** [open-wa/wa-automate-docker#24]
Hey i have a problem to access the API Explorer. My Issues, not the problem of wa-automate-docker. My only question is, is there a other way to look into the API Wiki. I need only the webhooks and links not the function to execute on any online page.

**Comment by smashah** [comment]
You can disable the api explorer by adding the flag 

```
 docker run -e PORT=8080 -p 8080:8080 openwa/wa-automate:latest --no-d
```
