### ISSUE TITLE
Could not resolve reference: #/components/schemas/EasyApiResponse

### ISSUE THREAD

**Issue by BHWarrior** [open-wa/wa-automate-docker#26]
![swagger](https://user-images.githubusercontent.com/490587/148684237-72625872-ed3d-4d60-8067-c5bd79984eda.jpg)

I got multiple error output when clicking into EasyAPI POST example.

I'm using WA-Automate Docker.version with Docker SWAG nginx reverse proxy.

It is still working, though. I can send text message to WhatsApp using one of its API. But those error messages bother me and I'm curious whether it will affect other function.

Also, do you have nginx reverse proxy sample for this? Here is mine for reverse proxy:

```
# redirect all traffic to https
server {
    listen 80;
    listen [::]:80;
    server_name mydomain.com;
    return 301 https://$host$request_uri;
}

# main server block
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name mydomain.com;

    # all ssl related config moved to ssl.conf
    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        set $upstream_app 192.168.10.10;
        set $upstream_port 8081;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

Are there other location directives should be added?

**Comment by smashah** [comment]
Hi,

Those errors are only related to swagger and this only affect SDK users in typed languages. The problem is tracked but has no affect on http API requests so you don't need to worry.

**Comment by smashah** [comment]
The issue is tracked here:

https://github.com/open-wa/wa-automate-nodejs/issues/2303

Regarding nginx reverse proxy, i don't have much experience with manual nginx. I usually use this:

https://nginxproxymanager.com/guide/

which imo is much easier to set up.
