### ISSUE TITLE
Use case for WA_SESSION_DATA

### ISSUE THREAD

**Issue by BHWarrior** [open-wa/wa-automate-docker#29]
I tried to put base64 string data into WA_SESSION_DATA in my docker-compose.yml. I copied those string from session.data.json which was generated automatically after connecting to my WhatsApp account.

Then, I stop my docker container. Started it again, then it still asked me to scan qrcode again for new session.

Did I miss any steps? Do we need to scan qrcode again even if we have put those base64 string already?

**Comment by smashah** [comment]
@benyhirmansyah most likely you have invalid session data or have been forced onto multi device mode.

set

`WA_MULTI_DEVICE: true`
