### ISSUE TITLE
Enable Multi Device in Docker

### ISSUE THREAD

**Issue by taufikterdidik** [open-wa/wa-automate-docker#30]
how to enable Multi Device in Docker?
I have successfully scan to link at localhost:7000, but it still not linked. It only work at legacy mode (not linked device)

**Comment by smashah** [comment]
@taufikterdidik can you show me your docker run command please

You should be able to just add `--multi-device` to the end to get it to work

Make sure to delete your old container first before doing this.

**Comment by taufikterdidik** [comment]
I use docker-compose.yml with "environment" config like WA_PORT etc, so I think I must use Dockerfile to add that param "--multi-device" to work on docker-compose. right?

**Comment by smashah** [comment]
almost every config, or cli flag can be converted to an environmental variable.

For example, 

in config.json: `multiDevice: true`
as a cli flag: `--multi-device`
as env var: `WA_MULTI_DEVICE=true`
