### ISSUE TITLE
Unread Messages - How to ?

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-docker#33]
Hi there!
just got to first use this docker version of openwa
looks really cool

can someone please help explain how do i subscribe to new messages?
something like subscribing to onMessage or getting unreadMessages

also, after I log in, how do I save my session

thank you very much :pray:

**Comment by smashah** [comment]
@fire17 `docker run open-wa/wa-automate` is a drop in replacement for `npx @open-wa/wa-automate` so you can use it exactly the same.

Use `--help` to see all the options/flags.

You can set a webhook to send all events to with `--webhook https://webhook.address`

Or if you are planning on coding your bot in node, you can use `--socket` then use the socket client to easily decouple your session from your process during development and production. The SocketClient has the same API as the Client in the main node project.

https://github.com/open-wa/wa-automate-socket-client-nodejs


How are you planning on implementing open wa?

p.s there will be a python version of the socket very soon.

**Comment by fire17** [comment]
thx 💜🙏 I'm getting messages

just need to understand how to save sessions
