### ISSUE TITLE
How to save login session ?

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-docker#34]
Hi there, 
really liking this docker version , its much faster then the python selenium im used too
was also able to get the webhooks working and will now start to filter the events

the only thing that i still havnt been able to do is to save the session so i do not need to scan and the qr and login everytime

would love it if you could advise on how this is done
thank you very much :) have a good one!

**Comment by fire17** [comment]
do i need to setup volumes for this ?
help will be very appreciated :pray:

**Comment by smashah** [comment]
What are you trying right now? Is your host account using MD?

**Comment by fire17** [comment]
> What are you trying right now? Is your host account using MD?

@smashah sry what is MD ? I'm having issues with the python version and trying out the docker which seems cool but i cant understand how to not scan everytime ...

**Comment by smashah** [comment]
MD = multi device mode.

Add --multi-device flag to the end of the docker run command. Keep the session running for a few minutes, send some messages back and forth then restart the container

**Comment by fire17** [comment]
ok , is that the official way to save the session ?

i assumed multi-devvice is only used if i applied to the whatsapp beta

I'll try with --multi-device
do i need to apply to the wa beta for this ?
is there a way to safely exit the docker?

if i understand you correct , just adding --multi-device , some interactions and time , and it will save my login

**Comment by fire17** [comment]
Got an error when running with --multi-device
```
- Launch inject: 293ms
- WAPI Reinjected
- Checking if session is valid
- Launch inject: 477ms
- The session is invalid. Retrying
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
- Launch inject: 293ms
- WAPI Reinjected
- Checking if session is valid
- Launch inject: 477ms
- The session is invalid. Retrying
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}

Node.js v17.6.0
```
this happens regardless if my phone uses multi-device beta
I'll try with different node version maybe ill change something ...
please let me know what you recommend :pray: 
@smashah

**Comment by fire17** [comment]
getting errors with --multi-device

Can i still just wait 5 mins or so and get the session save automatically (in normal mode) ?
Do i need to change the command afterwards?
`docker run -p 8080:8080 --init openwa/wa-automate:latest --license-key .......
`
How is the session data saved on the docker ? dont i have to setup volumes or something for that ?
thx :pray: 

EDIT : i ran the normal session , and exited the docker (with ^C) , when running again i'm asked for QR
maybe i need to stop it with docker stop ? or commit before closing ? thx :)

**Comment by fire17** [comment]
FINALLY ! managed to save my login :)
i understood it's not the best practice to use docker commit, if you can explain to me a different way to save login ill be very happy to hear (If not this issue can be closed)

i did (in another terminal)
```
# checking for current running container id
docker ps
# save current as wa image
docker commit 2a1fe72c441f wa
# stop the current container
docker stop 2a1fe72c441f

#And Finally:
docker run -p 8080:8080 --init wa --license-key ......
```
which loaded my whatsapp session without re-scanning the QR :smile: :heart: :rocket:

**Comment by smashah** [comment]
Glad you figured it out. TBH i am very busy on the main library nowadays

**Comment by willmaraujo** [comment]
> 

Hi, have you managed to fix it? I'm facing the same issue.

**Comment by Theblood** [comment]
This should be in the readme.md , it is very important.
