### ISSUE TITLE
 Package 'google-chrome-stable' has no installation candidate

### ISSUE THREAD

**Issue by HobbytronicsPK** [open-wa/wa-automate-docker#35]
I tried to build image from legacy docker file as buildin image works on x86 platforms.

I change [arch=amd64] to [arch=armv7l] in the following line, as I am trying to build it on one of my spare Raspberry Pi 2 lying around.

`RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list`

It is giving an error as follows;

`E: Package 'google-chrome-stable' has no installation candidate`

May someone help in this regard?

**Comment by smashah** [comment]
@HobbytronicsPK because google chrome does not have an arm version. This issue is also present in m1 macbooks.

**Comment by HobbytronicsPK** [comment]
So what will be the solution?

Can it not use [Chromium Web Browser](https://pimylifeup.com/raspberry-pi-chromium-browser/)? As it is dependent upon **puppeteer** and puppeteer does work on a Raspberry Pi.

**Comment by smashah** [comment]
install node, then try this:

```
> mkdir wa
> cd wa
> npm i  @open-wa/wa-automate
> npx @open-wa/wa-automate --ras-pi
```

**Comment by HobbytronicsPK** [comment]
I have changed the docker build file a little.

`FROM node:current-stretch

RUN mkdir -p /usr/src/app
RUN mkdir -p /sessions

WORKDIR /usr/src/app

#install chrome

RUN apt update

RUN apt install chromium fonts-freefont-ttf libxss1 -y --no-install-recommends

RUN apt upgrade -y

# skip the puppeteer browser download
ENV PUPPETEER_SKIP_DOWNLOAD true

RUN npm i @open-wa/wa-automate@latest
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /usr/src/app \
    && chown -R pptruser:pptruser /sessions \
    && chown -R pptruser:pptruser /usr/src/app/node_modules

USER pptruser

COPY . /usr/src/app

ENV NODE_ENV production
ENV PORT 8080

# Add your custom ENV vars here:
ENV WA_USE_CHROME true
ENV WA_POPUP true
ENV WA_DISABLE_SPINS true
ENV WA_PORT $PORT
ENV WA_EXECUTABLE_PATH /usr/bin/chromium

EXPOSE $PORT

ENTRYPOINT [ "node", "./node_modules/@open-wa/wa-automate/bin/server.js", "--in-docker", "--qr-timeout", "0", "--popup", "--debug"]
`

but is it giving the following error on running

`page.setRequestInterception(true); always throw exception " UnhandledPromiseRejectionWarning: Error: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found"`

still trying..

**Comment by HobbytronicsPK** [comment]
> install node, then try this:
> 
> ```
> > mkdir wa
> > cd wa
> > npm i  @open-wa/wa-automate
> > npx @open-wa/wa-automate --ras-pi
> ```

I tried this but it throws an error.

`✖ Error Failed to launch the browser process!
/home/pi/docker/wa/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: 1: /home/pi/docker/wa/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: Syntax error: redirection unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 Error: Failed to launch the browser process!
/home/pi/docker/wa/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: 1: /home/pi/docker/wa/node_modules/puppeteer/.local-chromium/linux-970485/chrome-linux/chrome: Syntax error: redirection unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
`

**Comment by HobbytronicsPK** [comment]
`npx @open-wa/wa-automate --ras-pi --useChrome` command resolved the issue

**Comment by HobbytronicsPK** [comment]
Now the only issue is, to **keep the session open**, if terminal is closed or Ctrl + C is pressed to free the terminal up.

**Comment by HobbytronicsPK** [comment]
managed auto reboot with pm2 + sh script + delay
