### ISSUE TITLE
How do I find the session data base64 string?

### ISSUE THREAD

**Issue by yinonhever** [open-wa/wa-automate-docker#36]
A comment on the docker-compose.yaml file says the following:
"Uncomment next line and add the session data base64 string to authenticate the session without the need to scan it again"

I downloaded the repo's files, built and run the docker image locally on my server, and scanned the QR code for the initial authentication, Where can I find the session data, and the base64 string that's needed to autothenticate the next session automatically? I couldn't find any file that was auto-generated.

**Comment by smashah** [comment]
session data is a relic of legacy (non-multi-device) sessions. If you have a multi device enabled account, it's irrelevant. add the flag `--multi-device` at the end of your docker run command to use the docker image with md
