### ISSUE TITLE
--multi-device The session is invalid. Retrying - Error

### ISSUE THREAD

**Issue by fire17** [open-wa/wa-automate-docker#38]
```
- Base inject: 10ms
- Launch inject: 219ms
- WAPI Reinjected
- Checking if session is valid
- Launch inject: 372ms
- The session is invalid. Retrying
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}

Node.js v17.8.0
```
I'm having this issue when running --multi-device

**Comment by smashah** [comment]
not sure what's happening here,. the invalid session results in the browser process restarting. maybe that's the issue? 

What is your exact docker command?

**Comment by smashah** [comment]
If this is still happening let me know. closing

**Comment by fire17** [comment]
This is still happening
running:
` docker run -p 8080:8080 openwa/wa-automate`
same thing with `--multi-device`, `init`, and `--license-key`
always same error

its been a while, im re-entering this project, please advise :pray: 

![image](https://user-images.githubusercontent.com/9356048/172823736-159ad8db-54c8-4012-840b-2d1927dfd35d.png)

**Comment by smashah** [comment]
> This is still happening running: ` docker run -p 8080:8080 openwa/wa-automate` same thing with `--multi-device`, `init`, and `--license-key` always same error
> 
> its been a while, im re-entering this project, please advise 🙏
> 
> ![image](https://user-images.githubusercontent.com/9356048/172823736-159ad8db-54c8-4012-840b-2d1927dfd35d.png)

show the whole logs please
