### ISSUE TITLE
API not working from docker

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-docker#39]
I am running following command to start docker container

`docker run -p 8080:8080 --init openwa/wa-automate --multi-device`

docker container started and I can show QR code on terminal, but when I try to access following URLs from browser but it is not working

> http://localhost:8080/
> http://localhost:8080/qr
> http://localhost:8080/api-docs

**Comment by smashah** [comment]
@manojsitapara what are the internal logs showing? Maybe the session failed to start

**Comment by manojsitapara** [comment]
Here is logs

> - session_STARTUP
> - DEBUG - PORT: 8080
> - DEBUG - flags: {"sessionId":"session","useChrome":true,"popup":true,"disableSpins":true,"port":8080,"executablePath":"/usr/bin/google-chrome-stable","inDocker":true,"qrTimeout":0,"debug":true,"multiDevice":true,"noApi":false,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":false,"noKillOnLogout":false,"cors":false,"socket":false,"emitUnread":false}
> - DEBUG - env vars: {"WA_USE_CHROME":"true","WA_POPUP":"true","WA_DISABLE_SPINS":"true","WA_PORT":"8080","WA_EXECUTABLE_PATH":"/usr/bin/google-chrome-stable"}
> - Launching EASY API
> - Selected port is free
> - Generating Swagger Spec
> - Postman collection generated: open-wa-session.postman_collection.json
> - API collections (swagger + postman) generated successfully
> ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.33.7                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
> You can also authenticate the session at: NA
> - Starting
> - Version: 4.33.7
> - Initializing WA
> - Using custom chromium args with multi device will cause issues! Please remove them:
> - Launching Browser
> - MD Enabled, turning off incognito mode.
> - Data dir: /sessions/_IGNORE_session
> - Data dir doesnt exist, creating...: /sessions/_IGNORE_session
> - Browser launched: 887ms
> - Setting Up Page
> - Loading session data
> - No session data file found for session : session
> - No session data detected. Opting in for MD.
> - Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
> - Pre page launch setup complete: 16ms
> - Navigating to WA
> - Page loaded in 1945ms: 200
> - Page loaded
> - Debug info: {
>   "WA_VERSION": "2.2210.9",
>   "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
>   "WA_AUTOMATE_VERSION": "4.33.7",
>   "BROWSER_VERSION": "HeadlessChrome/100.0.4896.75",
>   "OS": "Linux 5.10",
>   "START_TS": 1649474944386
> }
> - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2210.9%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.33.7%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/100.0.4896.75%22,%0A%20%20%22START_TS%22:%201649474944386,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%205.10%0A-%20Node:%2017.8.0%0A-%20npm:%208.5.5&labels=CLI,MD
> - Time to injection: 4898ms
> - Injecting api
> - Injecting scripts
> - Base inject: 31ms
> - WAPI inject: 440ms
> - Checking session integrity
> - Session integrity check passed
> - Launch inject: 643ms
> - WAPI injected
> - Authenticating
> - Authenticate to continue
> - First QR: 8635 ms

When I tried to access from http://localhost:8080/qr, On browser it says 
```
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by manojsitapara** [comment]
@smashah can you please help?

**Comment by manojsitapara** [comment]
Sorry there was issue with my local DNS settings, now working fine

**Comment by manojsitapara** [comment]
Reopening this issue, still facing issue on my local system as well as on server

http://localhost:8080/qr

![image](https://user-images.githubusercontent.com/12126671/163435751-1bd4981e-664e-4c85-a9f7-fc2826c51192.png)

@smashah can you please take a look. I am adding latest debug info again


> - session_STARTUP
> - DEBUG - PORT: 8080
> - DEBUG - flags: {"sessionId":"session","useChrome":true,"popup":true,"disableSpins":true,"port":8080,"executablePath":"/usr/bin/google-chrome-stable","inDocker":true,"qrTimeout":0,"debug":true,"multiDevice":true,"noApi":false,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":false,"noKillOnLogout":false,"cors":false,"socket":false,"emitUnread":false}
> - DEBUG - env vars: {"WA_USE_CHROME":"true","WA_POPUP":"true","WA_DISABLE_SPINS":"true","WA_PORT":"8080","WA_EXECUTABLE_PATH":"/usr/bin/google-chrome-stable"}
> - Launching EASY API
> - Selected port is free
> - Generating Swagger Spec
> - Postman collection generated: open-wa-session.postman_collection.json
> - API collections (swagger + postman) generated successfully
> ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.35.6                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
> You can also authenticate the session at: NA
> - Starting
> - Version: 4.35.6
> - Initializing WA
> - Using custom chromium args with multi device will cause issues! Please remove them:
> - Launching Browser
> - MD Enabled, turning off incognito mode.
> - Data dir: /sessions/_IGNORE_session
> - Data dir doesnt exist, creating...: /sessions/_IGNORE_session
> - Browser launched: 212ms
> - Setting Up Page
> - Loading session data
> - No session data file found for session : session
> - No session data detected. Opting in for MD.
> - Make sure to keep the session alive for at least 5 minutes after scanning the QR code before trying to restart a session!!
> - Pre page launch setup complete: 22ms
> - Navigating to WA
> - Page loaded in 1642ms: 200
> - Page loaded
> - Debug info: {
>   "WA_VERSION": "2.2212.7",
>   "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
>   "WA_AUTOMATE_VERSION": "4.35.6",
>   "BROWSER_VERSION": "HeadlessChrome/100.0.4896.88",
>   "OS": "Linux 5.10",
>   "START_TS": 1649954558054,
>   "RAM_INFO": "Total: 6.58 GB | Free: 5.17 GB"
> }
> - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2212.7%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.35.6%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/100.0.4896.88%22,%0A%20%20%22START_TS%22:%201649954558054,%0A%20%20%22RAM_INFO%22:%20%22Total:%206.58%20GB%20%7C%20Free:%205.17%20GB%22,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%205.10%0A-%20Node:%2017.9.0%0A-%20npm:%208.5.5&labels=CLI,MD
> - Time to injection: 2144ms
> - Injecting api
> - Injecting scripts
> - Base inject: 28ms
> - WAPI inject: 357ms
> - Checking session integrity
> - Session integrity check passed
> - Launch inject: 695ms
> - WAPI injected
> - Authenticating
> - Authenticate to continue
> - First QR: 6306 ms

**Comment by smashah** [comment]
.

**Comment by smashah** [comment]
This is only isolated to the /qr endpoint it seems

**Comment by smashah** [comment]
@manojsitapara Try this instead:

```bash
docker run -p 8080:8080 --init -d openwa/wa-automate --multi-device --ezqr --ev https://webhook.site/325f79ff-437e-4554-a67d-ABCD --ef qrUrl --ef qr --ef qrEv
```

There are some extra flags here:

[`--ezqr`](https://github.com/open-wa/wa-automate-nodejs/issues/2364): emits a simple URL which you can use anywhere to scan the qr code without exposing any internal ports/networking.

Looks like this in the terminal:

<img width="808" alt="CleanShot 2022-04-17 at 00 20 15@2x" src="https://user-images.githubusercontent.com/5903821/163694066-19e4896d-7a81-4e84-9784-42e746a50e29.png">

These qr urls are safe and random. How do you consistently get the qr url ? Via EVent webhook `-ev https://webhook.site/325f79ff-437e-4554-a67d-ABCD `

Specifically you need to filter `ev` to emit `qrUrl`, hence `--ef qrUrl`.

Now at the webhook address you will get this payload:

```js
{
  "ts": 1650151079220,
  "data": "https://qr.openwa.cloud/631c5",
  "sessionId": "session",
  "namespace": "qrUrl"
}
```

You can also add `--ef qrEv` which sends the whole qr code via the `ev` webhook. Those payloads look something like this:

```js
{
  "ts": 1650151198310,
  "data": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAAAXNSR0IArs4c6QAAHOFJREFUeF7tnduWG8cOQ4///6N9lqxM0uoLwU2yWuMR8hhV1wUECLJaGv/6/fv37//5PyNgBH40Ar8s9B8dXx/OCPxBwEI3EYzAByBgoX9AkH1EI2ChmwNG4AMQsNA/IMg+ohGw0M0BI/ABCFjoHxBkH9EIWOjmgBH4AAQs9A8Iso9oBCx0c8AIfAACFvoHBNlHNAIWujlgBD4AAQv9A4LsIxqButB//boHve2P6/ZrRj+8I2P3JyFni/a3n3fFDwWnzkn2dtea23X2+4v20NnfNmaKByT2U2ohcdqsaaGfBUAFePsMCXYxSCFHOqSOhBQteteaFvoxCkUOWegW+hMBQiAL/YgZMYeOu5M42dEF0iRodvR6klCktaN/Q0dXQctmMeIWRJDR+qTXj/putZ/sOqofvWodHv8/2kN2/TOHn5o3y4P9HhQvqvsjLQqJ/Tv0EJxlrnR/x8GUsLKkIgIgwSaXccS9LPRjFWGhx1c55T8lpTJsVmT7cWReC32O8Ar3qpA6MSJvXKr7s6PDPtaOHpfN6sLLjh73o6sSkYXeFDrJ5CRzb7elgp8du2oeUuaTRHnHazESv6kWZUp01WpS3XFU40mwVPczhCeb/a7r0auHmxIdaQmm1lRnria06Cwk8J1zEvFk7zw6eyfJhexdxfDqfiTCtjrnWeIhmFnou/fGHQFUX6+RNS30XltkoTf+3LMiajWLqXmjcpwENLq5rq5RzLaHbSsMyMVTNg6dkjG7xv6eQj1Hkugd8SSuPbV3xYUk539W6Z489GFYttRU81voCqHXtwQW+hGvTsIN0LfQ9y6jevuIyha6hf6FgB39hAvVSyrlCJp2zxF2dP0+fgVGKn5TYplqxVy6n4hFBXH17eVe5KokyvZ42eTxGEeIQSoFgi3Zb4RB9ZVep0K6IyYEH5LsppLUR/boHYJb6ITSscN3WpRqDDtrVh1dmUU0r4XeKN2rJDkrz8nNNZPIf6Pt6EfkqjG00HWbGfD077qMq5LEQuepKqqAOqKrxrCzph194Xt0Tq3nE52ehLh01HNmP9snEEJi0kpUsTxLcFdzrcKd7J2ImVRL5LK3ehfRwS/CaGjedY5OApztddScFvoRoax4OoQiCS6KYXavyhCqSWA/79R+FG8t9OafONoCSEpRO3r9r8Z0SD0lLAv9EIU5R+8EOJvlletMCXSq1KsSzuc8tnGq1cnG7C5s79ADWMNC75SBqtSz0Nl3CapVl7orySaByXgCEaKhpOrZTGyhW+hH9zy7xHO1xJIWUi8YbKHvbuz/tlLvHa7jNdkXg0iFBrSLht4udLS7ocGd291VX18kYiG3qxMXiWfOfLUHgq0iW9b9VTLO3t3QkrtKR3Xu6rw3PFcv3W/Y3PHqsPHPQFnoccQsdM1oC11jNDKCkHG/oIVuoXdJ+JFCV68ptqB2BFot3zpBJeV49WykbO3cRldxIGvu18h+u0xxqPoFKMKZKj77diEyFnVO0tIVk029dCebr4pBBYGIRc111ROrc1bPRvZORFfdj6qAsuJV/XJkAFOYWOjHrveWf8BhinyEjETYnWxcPdsUqck8BBOSXOzoR2RJVWhHF8y8g+R29GcQ7OhHMmZbC8Whv1rodzhdp0TL7q+TTO64AFQunRXoXWTMvnp7nIu4Ipm3ypussKMK52ztYt+tQv/SJS0r3bNCWlWOK/Cy+7PQNZ9IkiCCtNA19skR6y7jskKy0J8IRKRWGGVLv2qFochkoff+wKgyJYV/4nMLXYFkR1cIsT8WYkePL+402qURc0Iny1fFozJfth8lPVR1r3uXVmtOOfqUu0b7VXF4aQ5332bsPDvRW78jnnfFPsDHQn+AQy5ZSEtSLZXVGtV5O+KdSqIWeu9XcAS/TbwtdAv9eEdw5gwWOuvDq8m4k+Tf4ujkoNsNFjOW7ByikpZ8Fl2MkSB1qoipMj8qsckFoDp3Nr7VtkMGvzhAlflZjnfmKW79ULyNvV6bIoaFzv55JCWyLJ6dedSzFvqrOkhCs9AhAsS1q46pCJ+dlzgAWTOCrDOPetZCt9AP3Ms6ENQ5+nfQsoJ87GHFWAtd3xuQ5EK58jWexIFcdP5Vjk7AU0GJxFIV0uT+ormqiYn06BGJSMvUISPB8268aMKNKgzF1atnScUYxWxREqjfupPAK/As9Fc0VfLoJIntStFNuooZiX+2dJ9qLcjelWtnk5aFLt5Tq2xsRz9SzUI/YkJ4YkevpmnxnMqwdnQ7uqJeh0NZV36MU+t8XOmueokqYKR8i8ouVf5m11HzEHfNjiXYqtJT7f8KB1KKZt8nKzGTz8maWSNRdyErsNwnl0XxrPfohIwqgFkAyZrZOc/2FvWuigzVspCQkfTWVRwsdPZjnaxx7FtVC/0EOQv9CYqFXv86quLQlnZk7I8VunK2qdKq2l+REqjjXtlyXAmUEOyOtkhVYdXPq7wg6xGBroo94S05W3FsvXS30I/uusekeoegiGqhx3RX+GWTqpqHxCFq6YriJY9Z6Hun3fdQnWBb6Ecu2tHZvz1P1ByMtdAtdF2ZDJHtzzQW+g8WOnFF4oKkdJq6fZ4k/VU5p861QiwkRqtaFNLXKoyu5lJ3NyS+d3xJp8rb3TnucXRCIgtdf2nDQtcYWegvCFjoKoNXnUPNG7miWtNCt9Ahv+aEHi1MHL1TvhEBTN2CKlFmy3NSBq44pzpHtYQkrx/3sSdfXILETw3v8JbgdcM5LXR1QaQYoQRioV8jqMRwgwDC8Froiv37mwDxJ3+zYlEXKSucTh01u/d9QiFf1FCXX9vPqw6qzqFEeYVTdT+P+Sx0xb7053Z0O/qTLBb6UTR29AQxSK+dzUsEeOX+2f111ox6zsilleiye1e4Ro5JnFhhpPbx9fnUPNn1zsYR7LM/RFLnuqFyqTs6AYSUnlGQOoCR/WYDSMvLrHjIXjvYWujaxbNJlbRi5BVyJ2ltnrXQz4C00Hv/es1UP1+dpyMOkmSzPOkYVOcsFrpALxtAO/p5f18VqBLEEOnDaSz0HTwKEPJeuFoerepzt/Mq0mbLcZoUtnvolIXRPNE5V4luVbuQPctPiidIfOtKdws9/hdXFOEs9Fcak8vVTg/8NyVuC735VsCOPvdnlPZktKOzf02VGEIg/HWOXhULORjJvhHhsq0DyKB/hpKSm+AV7aO6ZtQG0XNn2wU1L+HCHRUQ+UJWde8Kk+LnFroCrhOwqujesaaFfmQCuacgYxXnFnxuoStQ3yG6d6xpoVvop1pQt+6kFK1+M8ilOyPnZMxUgvz6nKw5lWxIJTVVjv9YR1eBJuLtkOEqoSjgp9Zc1d9Xe04Vl6vPp261H/Nnv4cwGaPsWx51TiL8bOwV1zoVXDLe9dJdLWChz/1tMOJQKi4W+isCKtlULxaziWefGKvxE89Z6IuA/TPtVKa20HWUssKyo2ss0Qg7uoX+IAxJUkqEE6WyWsOlO5I5G3zHlyjIjrLuQPrRM9Jf3S+ovXYuIdXcX5+/ew2KbXQuYjrZefbjVALJxpq0EtlYPvLt799T9SVYdT/UQmfu/24RTlGGXFJ1BGChW+in6cmOzn6mWs3xFvoRuU5CC+JQd3QVpGypErk7vdAiTjdVRawiebYf7eBHnK46VpW41VI5mvcubkYcn+JilV+75yz0s2RCglQNBCEjEQtxhKp4Vek+hR/BiFRhUyZkoe+YqYixHU6IqtwsG4ipixQiekJiC10ja6GHGNnR7ehPgqhkXHV/kqRI4nbprpPfZkRd6GQZ5V6KZF9rkXmmKgPl9sRJqu9oq89lBHwVR4LfHaW6ikOWj2QexUuS/LL7IxzPznnb67WpzZN5CFEjJ1HEsNDnbuhJwlBcuBKBiifp3y30HcoqKCpz2tGvc/cUtqpsrlYV2dg+1rfQl/1DGnOluyJcVGZErkgINjWWXA5WX9OBsuswdJV4onNHTjcl0I7bkj1Uz6mSYbWKmKoKA05Z6EpwqgWw0Oec2EK3o5/qUYmQOHP1UspCt9CVWagEZkcXr30sdEUxJsJqSUvK5u8wtnrOjyzd7xDZ/oJG9abkFjR7p7AqG3fwm7oZJqLTKeW/EdV5q8+pva2qusidUDZmipdKAxdY1Hv0DlHJZqviVWsoQL8As9CVjI6fVwVbfU7t0EJv/HrNQn/Sq9pfdfDLuoOqiO4Q1l6EK1zQQlcIWOgSITu6hOgwoJpAqs+pHdrRB4Uega3K6OztuCq3ibtm90vWJJc1VWejVUTW/acqDCW6aD9E6GRsxK+o4iCxV2OzcVAcIlrazDXXo2eFo4gQEU6BaaHH6JLkQsaqmF59rqqlqaRgodvRTzlIEkZVENXn7OjPkNnRUXqdc/Qp4kbbJ45OSqC7qogqRqRcq56FuGtU7ircSQmr4k3m+hpL5kRS2g0mMeusk3zWQj9zh6qjKxJZ6K+0VGJQeFroSZl3/grs5OWNCng2GxMhRWK20PV3rrMiq5bYqjwnVQXp0dPSEQOznJ5aT8xjR7ejPyni0n1Wcj9W6FGGJSUYgbvq4HtxRyRXAshWBsShCElWYUviqTCquv8UtqRCI/yrjiV8q66xe27O0QkxhjYf/p0z1Vpkv0ShSDxFxqwY9thZ6E9Esi3CXXhFHLfQYQawo7NeGsL7MnwqoVVjRhL3O0yHYGuhE7SaP2G1ozOwLXSGlx39BIFsT6qyejUU1XfPZ5dY0R6y5aUqz6uuWN3b/pyq/CX7ywqCrEl4oubN7m8VtlltCO5/jx49exgSQCJ6C123AORCy0J/ZZ9KJqRaIrzejLXQzy5ypkitnDl7AUcSHBm7Xb9DxqgnJhh0euuqWNS57ei/4txCsno2SFUSF7Pgn8cUEbLVSIfwHSFVsSUEr8ZFYRslwqk26I7kos5Z5RDg9T2OrkheJeMNAFnoJ2wirxw7vauFDqQcD7XQFZSrsrGalzhqVIJXkyhZ345+rPxWtX+KrxefW+gKOCXIalWh5iVCs9Bf0SJto0t3pYDd56RnmnIA8sWD6poEhinxknlWldGrsI2+vzBV5pMk+R14SzhWHFt3dNV3k/4q64pKrBGJ1LNFAF8eIwLtOMnfjK2Frv+J6gku7n349++sysTq3yEzWuhxr0gc046uf9GXlc4dJqPkWRa6cq9On1TNaO++AOlgQkRYxYc8R4Rere4UXlHlUl2TYEDW6Mx7A2/rpbsKkoV+DH3WAe4iWLWXVefIVneKQxb6GIcs9E4mpoJUArnaCxHE1Hns6EckV8XBjg5ZewNg4Y4UESx09i/b2NH/Mkf/7gKYajOUkMllYZbkU9iSedTl0lTprvDcYqT2/zVWvY4k3lLlDTkX2U8w9p7SXQWhenA1bxakasD286tzWOjM0RWeFnqW4Qv/AYc7ymgLfe5HNwrLKJ7EJVfxQu3fjk7S5iaBKGBXBbSSxVXes6OzhOHS/cmoKm+KklM0jj6vl+6tVXc/cc26xRTB1G15NRBqf9kkpdYnLUCWjGrNTryvzt1ZUxlNdr9ZfM7my+5/ihcquSzp0bNAno2LDl797LFO9hLIQn8iECWMTnxDa9kk+axQMhyq7tdCryKXeK4qZpUZLXT2FVgLvV5+E3dVvM1WemTNnQzXle6ERNmx3wAwVDVUE5rKlSShZbFVVY7a0/bzqksShyelO9nP1NhsVbMfRzAAMbHQAViHclcFyUI/okuSVFUsKi6Rg1roUBHESbJj7ejH3lqROoutHf2JgIVuodvRkxwgYsmW/J1ERPYzNbZajXz70p24LQkaeR8fkaZaMqpesEoMNW/1LEktymFThOucc0osZA8SmM2ALEZqfcLx7Jq7c8z16Ba67kdJQC30WHIkcSuhEXFXKhC1PuGFhb6L1h4QQozoskb1xNmLHhV8C91CP0PAQrfQq8Z0+lyRUIe5OgnNpfsRgWJc5kr3qO9Wm1txM6zWrDpvVCmQKqJTGZDyMVvJqNarGiMi1lX4jWbAzWRZbDvrq7gk57bQH0B13ndHAphysw6hss8qQlno+g6GJOCkQENuZud4ULz8xyHVIoQYZGy2f7ajP5Gy0BVT659nsa2vwL7SHKxTFzpxK1WmdubKglgtuVU5SV6vRXudunklWN6xZgefaH8kkWfN4TGus98rR1cxmYqDhX4SwGzJbaE/6VMVQPW5/ZqqtcgmfCK6/ZzqWQt9h5gSTzZoZJwd/YjWlJNUS1glHDt6HDPAf5fuZ26VdfuO00XtDBHAO1yHrGlH7/31HtX2JsU+J/Rqz7S/MKo6rwJEieeq7Joi9eQ5iXiycVH4TLl/kph4WLaqUOckC1crjs4esvHcncNCPwssEVI2QVjoREJ8rIUeYmahW+hPBJTL2NHZHUfVLFSKu93R1YayGVaRrApYEZAD6dU8U98BUOtc4U1uozsxIUInVc52LNkfaami/agEN3EWFdsqh5QGN5/XHV0tQoJGxk4RI9o/AZ6MjfauyGChx4zLCrbzxofEiPCCjFW6u/jcQj8DhgBPxlrodbEqkVnoi3p0lVmIS5OxdvRX5F265+4YvlCzoyvl7j5XGZT0dNU+PNpyJ6CrejqF2dV5lJtlk99+fhIjSI/L4WTNqXOTeQiW2XlV3FdhMtKj37V5tU5WHO+YZ1Wyyd4vKHESgqm5sp+TNbNCeqxdrQo7WGb3p7i3ChMLPctK8R15NY2FfkRoFakt9EU9+l1ZSq1jR4979mx7U8VZJbtOu5B1TDu6jEL91r1DDOJ0U/07WVPCthmwgowK28gVo3N2sPzu58zGTGGbnUeN62CdTc5qD7eU7mSz1bKLBM1Cr//U9BFLCx3IqvGzXrUKiYOFnvjKpwL863MCfDahqQRmR2eJZxtLhW027mrcj3X0zsGIWLJBq8452e9F77jJ+29Fqu/2+V1i2p6bXPJdPbfHsROjbFJXa0Z3HCDucz26hX6E3UIHVGwOtdBDAC30M3iq2VhlZ1JyN3n/1sft6PX3+gq7YqVqoVvo8zlBkXV+xdeenaxPKlEisqpZqL2TPSy5jCtu4M9esqBM9kzZ/RLg1diI4KT0JGOr/ehQbyh/574CE1VZZTGZmkfxgsQzy9vd3u9xdJXBLXTmSIQYWVITMqp4bj9X81ro9diDOFjoCixF1KroIsdctSYpU+3o+nJ1RRIlsVfcdekOvgBCgFdjV7gXWdNCP0aAlMLZypOU/I+xxCzIfkeErg6zYvNTpFb3AlGmJsEm+80mAYL7/pyEJOQ+pHpO9W3Fzn6rbttJhivWBK4dDa2X7oRwigjZgKp5skBb6Jo+Fjor3UmrQ7DVkUqNsNAVTMp1qu6v1s0mLUWa7efZhHqWCKecjuDV2e8Uftt5poxGxYxwIzn2HqFPuv8dAZwiWDXLq/Uj8VZJVH1OJYWOOMg5k4Qf+3HOYz0Vp+yeOhgl17DQFVEVkFNBIs5LBJAlo4XOS/UstndxKFjHQrfQn/Sw0C10lZAwUSJSrXBIVWZNkjwCK9vnKqewo+t/WeYqDgpb0pOTuSJeTHF+iaMTcZCxqazyzyACUNQvd16ZkdeI2SRA8FIYRPvLfkZisq8Opi4ziagUJvQ8mfHZJH42F+EQwWGzVr1075CxuNkDRp2AZsFVRM3Oo8hSFZ3CIDsviac6C6k4tnNFWBPOKEzU/iufW+jN/m+q5LGjx324hV6R93/P/Fih72HplL9ViJXbZkvlVcmkur5yJEKqOyqOKInehW3W8UlCI3FQY7McV5zOnnO3Xr10t9CzoTsfR8RKhDR10VmtgB7PZck4JY7OmlNxmDqLhX6iFwVK1VG3z00FsCPWzrN29Ff07Og9g0r/8YjHMlPisdCPQbOjx0S20JtCJ70YuV2tJoVs+aiOTYih5spiRBKYGlstTQl+JLlk3wLsDWHqnJ1zVSsrsqZqiYtzzfXoWRKf9VPV1zETpbkSp4WuEKrf5itsCS+yCY0IRZnMijUtdM23lxEkoJ0kBbd1OZyQejvJlNMRtyJkrLq9Hf2JskqGSf7Z0RVQQ0CrZV4CqsRroTMBREmUJHmSDKtrkiQqSfXfgHVCV2UP2OS/QycFUC37iUNVznjnM9nSs7OnO+5jlAAJF6fuELZ7qq7/Vzg6OVyWSBZ6FqncOAv9iJOFnuPOv6MsdAjYG4Zb6Ba6pB0RsnLi7MUZWZOUc2p/1TJf9VtXvbY6ZxYvFURyAfiONaO7iGpvfVeso9KdYDl0R1Tv0RUZoyBVN0/WtNCVzF8vtJQACDmzIlRrWujs0jHA3UJ/gEMIpxJIluTRPCqhvUN071jTQrfQtV3tRqy6/SUCiAQcXQJ1kks28ahkR845taaF/pcJnRBVuVm2JSDErLYSpAffVw6dc2aFhLPh5gFyUTc1trPfqZ74DmyjNQhvAV73lO4W+hMB4tor3AwQI/ypKUmMZCzZHxHklHhIcq6eZWqvu/Ut9AcgU2RURLDQ879VrwplMp60Yuvs+etZC/0ERdJ33+EAFvoR5akkSkS0ak0VX7LHq7HfTugTh6JzKKBJr0jXzgSG7E+NXbE/kuxIuxU5HyHu1NeLiQFkL0g7lYKKNan0CJ6buNRL9ykiknkIYHeVXdUgqbMQXKKxWWKo/WTn2Qui+txjHoLtFgML/cAIC70rKEJGMra7L9rzWehHxKdeORJsyVjAkbrQ1YbAJsKhRBxV96g+t3cddWZSJm7n6pS0EX5/E7advptwtYrJVIwUh4qfW+hdsXaSRFRuWuhx6T6Fe3QXoRLEO5KohQ7+zPCqPlIFwY4eI0Rc0UJXbHv53I5uR38SgriXoth2ro4gs45J9qPGunTfIdTpmSKwSVafKrtU8KMymjybff1HLoGmBKriqda5akPUvFkuEExITPZjq+fMnkPtbdE55xydZG4CylSGjZKCAt9C145voV+zqJM8OolysyMLnYg8U+JG89nR2VdgoxZgSACHcHVEeRX7zpxD51wn9Orh3lG6V/dKy75sz0n2QxNVdXw2SZH5SZmqCJ+9F1DYkgqSnPWq4qnOAZ+z0KlLdwhvob/S00KHcq0Pt9At9Bx7OgnuagULPYf9wCgL3ULP0chCz+GUGTV1cZ1Z658xP0voUR+kejwA2svQbG+o5idfpiFrqp5U7evr8yo5O3cu2b09xk3tb2rNKu7Vc4h9W+gksGdjieiitSz0XiSqAqkKUiWX6rzVc1joX7XLr/giqEozCz1Gzo7OmGWhJ76m6dL9SKqqs+xnqhLQQrfQ/0Ug+9qJQPYOgpN7gM7+yLteMpbgGyXV7WekJdmvTzDKnpMkLLV+9YJSvW2I4kD2v5nn7+rRCRFVkLJzEWAtdFZRKGxJDC30kNEWuhK8ImPkXtWMT/akxJAVgFqz6jJ29CNyP8rRq8QhrkhusSNwpwSpkkJ0cZf9bH/bq4SeLbGr8Tp7LnsWRXjS0hEcqkmryjfFabJ3xbGLPa5z9CpxFCjZedU82dvyySDcIYAVJM5i/jXujnOqJEH3/DW+KKTw3wYgXFT7Lu7PQt875NSF0LuczkJXUok/LwrJQqewq+yXnU/NY0fPIsnH2dHZ37ubrBqXl+6cDrknyGUSycZZMu53SdaIqoPOvUD1WfJcZ2z2Ak4RvIP1FbuUAWyf6+yP8KuDdU5F/5sr3ZML4mEW+hEyQozt0+S5zlgL/fUv8qj7hA7WSUFZ6Gc9epaoSZD/HTbVLhBiWOivUbKjQ9aqsgZOdzncjm5Hn+LSYx4LfRJNz2UEjMB3QqBeun+nU3gvRsAIhAhY6CaIEfgABCz0Dwiyj2gELHRzwAh8AAIW+gcE2Uc0Aha6OWAEPgABC/0DguwjGgEL3RwwAh+AgIX+AUH2EY2AhW4OGIEPQMBC/4Ag+4hGwEI3B4zAByBgoX9AkH1EI/B/3NJc1SHhAMEAAAAASUVORK5CYII=",
  "sessionId": "session",
  "namespace": "qr"
}
```

Clearly there is something wrong with `/qr` url networking within the docker environment. I suggest using the above method of getting the qr code.

The good thing with getting the qr via webhook is that it updates as the qr updates, whereas using `/qr` or even the easy qr url require you having to refresh them manually.

**Comment by manojsitapara** [comment]
Thank you @smashah !! Your suggested method is working using webhook, but I am still not able to figure it out the issue why it is not working from Docker.

**Comment by smashah** [comment]
@manojsitapara I don't know either. Best to give you an alternative until this is fixed. Till then the issue will stay open

**Comment by smashah** [comment]
@manojsitapara it's fixed now.
