### ISSUE TITLE
session.data.json empty (only e30=)

### ISSUE THREAD

**Issue by WEBudoGT** [open-wa/wa-automate-docker#52]
I'm running with docker-compose, and either using MD or not, I can't get session data saved to file so then I can enter the info on docker-compose.yaml
How can I get session data and save it manually?

**Comment by smashah** [comment]
https://github.com/open-wa/wa-automate-nodejs/issues/2782#issuecomment-1175288280

**Comment by smashah** [comment]
The session needs to be authenticated within the container and the container needs to be maintained to keep the session running.
