### ISSUE TITLE
sendLinkWithAutoPreview API not working

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-docker#6]
I am trying to post message with sendLinkWithAutoPreview API into 15 WhatsApp groups via python code for loop, sometimes it post only in 3 groups or 4 groups and after that process get stuck and all rest all API stop working.
Note: sendText API is working fine without any issue, it post in all groups.

To get start working of other API I have to restart my docker container.

@smashah  Can you please help me how to solve this?

**Comment by manojsitapara** [comment]
it's working, closing this issue

**Comment by jorgitobg** [comment]
Hi! same problem here... how did you fixed it for sending same url with image preview for lot of whatsapp groups? Regards
