### ISSUE TITLE
WhatsApp QR Code in Red color

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-docker#7]
Why QR Code display in red color? How to change to black color?

![Untitled](https://user-images.githubusercontent.com/12126671/102089617-7bc1e380-3e42-11eb-9499-1f8a9ae69c3d.png)

@smashah  can you please help me?

**Comment by smashah** [comment]
@manojsitapara I set it to red so people don't get phished. Soon I will be adding more colours which will be set randomly but it will never be black - unless the system completely stops working without black.

Thanks.

**Comment by m7mdcc** [comment]
Sorry to bump this but i tried it today , its not work . when i scan it , its say make sure your are on web,whatsapp.com

**Comment by smsalarmas** [comment]
It would be good if you accept a color parameter, at least 5 or 7 colors, you cannot develop a professional system with that red color.
