### ISSUE TITLE
multi users?

### ISSUE THREAD

**Issue by the-jojo-jj** [open-wa/wa-automate-docker#8]
Hi, 

Can somebody help me with multi users?
thanks.

**Comment by manojsitapara** [comment]
You can create docker container for each user

**Comment by smashah** [comment]
You no longer need docker-compose to use this project:

```
> docker run -e PORT=8080 -p 8080:8080 openwa/wa-automate:latest
```

You can then deploy as many as you want with different names

**Comment by manojsitapara** [comment]
@smashah you made it so simple !! Thank you !!
